import Head from 'next/head'

import { useState } from 'react'

import { Configuration, OpenAIApi } from 'openai'

import styles from 'styles/Home.module.css'

const Home = () => {
  const [prompt, setPrompt] = useState('')

  const config = new Configuration({
    apiKey: process.env.NEXT_PUBLIC_OPEN_AI_KEY
  })

  const openai = new OpenAIApi(config)

  const generateImage = async () => {
    const res = await openai.createImage({
      prompt: 'Say this is a test',
      n: 1,
      size: '1024x1024'
    })
    
    console.log(res.data.data[0].url)
  }

  return <>
    <Head>
      <title>Create Next App</title>
      <meta name='description' content='Generated by create next app' />
      <meta name='viewport' content='width=device-width, initial-scale=1' />
      <link rel='icon' href='favicon.png' />
    </Head>
    <button onClick={generateImage}>Generar imagen</button>
  </>
}

export default Home